[repository]
name = "pas-plugins-identity"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/collective/pas-plugins-identity"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "pas.plugins.identity"
path = "backend"
code_path = "src/pas/plugins/identity"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@plone-collective/volto-identity"
path = "frontend/packages/volto-identity"
code_path = "src"
changelog = "frontend/packages/volto-identity/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-identity/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "91c845557fce11a401a959f763add9d1384b135f"
generated_date = "2026-08-20 21:33:55"
