/**
 * Action types for the identity add-on.
 *
 * Namespaced with the package name: Volto merges every add-on's reducers into
 * one store, and a bare name like `LOGIN` would collide sooner or later.
 * @module constants/ActionTypes
 */

export const LIST_LOGIN_PROVIDERS = 'IDENTITY_LIST_LOGIN_PROVIDERS';
export const START_PROVIDER_LOGIN = 'IDENTITY_START_PROVIDER_LOGIN';
export const COMPLETE_CALLBACK = 'IDENTITY_COMPLETE_CALLBACK';
export const SEND_MAGIC_LINK = 'IDENTITY_SEND_MAGIC_LINK';
export const CONFIRM_MAGIC_LINK = 'IDENTITY_CONFIRM_MAGIC_LINK';

export const LIST_IDENTITIES = 'IDENTITY_LIST_IDENTITIES';
export const START_LINKING = 'IDENTITY_START_LINKING';
export const UNLINK_IDENTITY = 'IDENTITY_UNLINK_IDENTITY';

export const GET_MY_PROFILE = 'IDENTITY_GET_MY_PROFILE';

export const LIST_DRIVERS = 'IDENTITY_LIST_DRIVERS';
export const LIST_PROVIDERS = 'IDENTITY_LIST_PROVIDERS';
export const CREATE_PROVIDER = 'IDENTITY_CREATE_PROVIDER';
export const UPDATE_PROVIDER = 'IDENTITY_UPDATE_PROVIDER';
export const DELETE_PROVIDER = 'IDENTITY_DELETE_PROVIDER';
export const TEST_PROVIDER = 'IDENTITY_TEST_PROVIDER';

export const LIST_CLIENTS = 'IDENTITY_LIST_CLIENTS';
export const CREATE_CLIENT = 'IDENTITY_CREATE_CLIENT';
export const UPDATE_CLIENT = 'IDENTITY_UPDATE_CLIENT';
export const DELETE_CLIENT = 'IDENTITY_DELETE_CLIENT';
export const ROTATE_CLIENT_SECRET = 'IDENTITY_ROTATE_CLIENT_SECRET';
export const LIST_KEYS = 'IDENTITY_LIST_KEYS';
export const ROTATE_KEY = 'IDENTITY_ROTATE_KEY';
