Added the `[server]` extra: this site as an OAuth 2.1 authorization server, installed by its own `pas.plugins.identity:server` GenericSetup profile, which also registers the browser layer everything in the layer binds to — a site that never applied it does not publish the endpoints at all.

Clients are registry-backed records, exportable through GenericSetup like providers are, but their secrets are stored hashed with scrypt rather than masked: this package is the server here, so nothing ever needs the plaintext again. A secret is returned once when minted or rotated and cannot be read back. Redirect URIs match exactly, public clients are flagged as requiring PKCE, and an unknown client id costs the same work as a wrong secret so the two cannot be told apart.

Signing keys are asymmetric and generated when the profile is applied, never shipped — a key inside the package would be the same key in every site running it. Only the public halves are published, as a JWKS. The ring keeps previous keys so a rotation does not invalidate tokens still inside their lifetime, and it is bounded so the record cannot grow forever. Access tokens are self-encoded JWTs, so issuing one writes nothing to the database; the issuer is configured rather than derived from the portal URL, because relying parties compare it byte for byte.

`@@oauth-authorize` issues a code to a registered client and `@@oauth-token` exchanges it, both as browser views rather than REST services because a relying party sends a browser and posts a form, not JSON. PKCE is mandatory for public clients and only S256 is accepted — `plain` puts the verifier in the authorization request, which is the exact thing PKCE protects. Codes are single-use, short-lived, bound to the client and redirect URI they were issued for, and burned even when the redemption fails, so one intercepted code does not become unlimited guesses at the verifier. The token endpoint accepts HTTP Basic as well as the form, which RFC 6749 §2.3.1 requires and most clients use.

Refresh tokens are rotated on every use and revoked on replay, issued when a client is **registered** for the grant rather than when it asks. The client-credentials grant and a Bearer plugin complete the picture — an issued token authenticates a request against Plone, with the audience checked against the client registry on every one, which is what makes deleting or disabling a client this server's revocation.

An unauthenticated end user at the authorization endpoint is sent to log in rather than refused: answering the client `login_required` broke the flow outright for the ordinary case of somebody not signed in yet. A visitor already signed in to Volto is not asked again — the endpoint reads the `jwt_auth` token Volto keeps in a cookie, so a Volto-first identity provider is a coherent thing to build. @ericof
