Added the `[content]` extra: users backed by content objects, installed by its own `pas.plugins.identity.content:default` GenericSetup profile.

An `UserProfile` Dexterity type, a three-state workflow (`incomplete` / `complete` / `deactivated`), and a dedicated `portal_identity_catalog` carrying the whole PAS property sheet as metadata. Where Profiles live is configuration rather than a constant — the container's parent, id, title and type are four registry records — and the catalog indexes a Profile wherever it actually is, so reorganising content is not a deauthentication. Drift is reported by a read-only consistency check and repaired by a re-runnable import step, kept apart so the check can be scheduled without a side effect. Uninstalling removes the catalog, the type and the workflow and leaves every Profile untouched: uninstalling an add-on is a configuration change, not an instruction to delete accounts.

Its PAS plugin serves member properties and user enumeration entirely from catalog brains, so a site can back its users with content objects and still answer "what is this user's full name" and "who matches 'liddell'" without loading a single Profile from the ZODB. That is measured rather than asserted: the tests patch `ZODB.Connection.setstate` and require the load count to be zero while enumeration and property reads run, having first proved the objects were ghosts and the counter works. The plugin sits above `mutable_properties`, so a field the user edited is what the site shows rather than the claim their provider sent — including a field they deliberately cleared. Login names match regardless of case at both ends. A `deactivated` Profile stops being enumerated without being deleted, and which states count is a registry setting. Property *writes* go back to the Profile through the same plugin, so changing a name through user preferences, through `@users`, or on the login path is stored rather than silently discarded.

First login mints a Profile in the `incomplete` state, seeded from the provider's claims through the provider's own attribute mapping — the one the control panel edits — and files it in the configured container. Later logins refresh only the fields the provider still owns: rather than a flag per field the Profile remembers what the provider last wrote, and the provider may write a field only while the current value still equals that. Editing a field ends the provider's claim on it, and so does clearing one — the case a flag-based design usually gets wrong, where a value reappearing at the next login is indistinguishable from a bug. The login name is never synced: it is half of the case-folded index enumeration queries, and a provider renaming somebody should not silently move their account.

A user gets `Owner` on their own Profile and nothing on anybody else's, computed by a local-role provider rather than assigned at creation so there is nothing to keep in step. `Owner` is what Plone means by "this object is yours", and it carries more than editing: stock Plone hands it sixteen permissions with acquisition on, so `user_profile_workflow` states the ones that matter and stops them at the site administrator. Deleting is the one to keep in mind — a user deleting their own Profile would break their account while their login kept working — and adding content inside somebody's profile, rewriting its view template, editing its ZODB properties and opening it in the management screens are the same shape. Every field declares a read and a write permission, and those permissions are granted to somebody. `GET @my-profile` answers the frontend's first-login routing question from the catalog, so the check every login performs costs no object load.

The type also carries the picture, in a field named `image`, and it wins over the member portrait: a picture somebody chose beats one a provider supplied. The name is load-bearing rather than a matter of taste — `plone.volto`'s indexer looks for exactly `preview_image_link`, `preview_image` and `image`, and what it finds becomes the `image_field` catalog metadata every Volto listing and summary view reads, so a field called anything else is invisible to all of them however correctly it is stored. Both the read and the write path honour the precedence — a portrait uploaded through user preferences lands on the Profile for a user whose account is one, and on `portal_memberdata` for a user whose account is not, and `@portrait/<id>` serves whichever store answered. One store per user, and it does not change under them.

Both types are addable in one place only: the container the registry names for them. Each has its own add permission, `rolemap.xml` grants both to no role at all, and the grant that makes either type addable is written on the container itself — when this package creates it, when it installs into a site that already has it, and when a folder appears at the configured path, which is the case a policy profile or a content import reaches. So a `UserProfile` cannot be created or pasted into an ordinary folder by anybody, including a `Manager`, and neither type shows up in the add menu anywhere else. Filing principals somewhere else as well is a grant an operator makes on a folder they chose. The permissions are separate per type so that a site keeping groups apart from users can open each container to one kind only.

Content-backed groups come with it: an `UserGroup` type, three PAS plugins (`IGroupsPlugin`, `IGroupEnumerationPlugin`, `IGroupIntrospection`) and a `group_ids` field on each Profile, so group membership is content a site can edit and review like any other.

A Profile's `userid` is genuinely permanent — an identity record, every local role granted on it and the catalog entry the enumeration plugin queries all point at it, and the REST API refuses a change rather than detaching all three — and `email` is required, because the audit log, `@users` and magic-link join all read it. @ericof
