Added the core identity layer. An identity store maps `(provider, subject)` pairs to a permanent canonical userid; a driver framework carries GitHub, Google, generic OIDC, email and `plone-identity` drivers; a PAS plugin provides extraction, authentication, credentials reset and opt-in challenge; and authlib-backed authorization-code flows carry state, PKCE and nonce. Five documented events are the package's public API, and everything built on top of it — the audit log, the `[content]` extra's first-login handling — is driven by those events rather than by reaching inside the flow.

The pending authorization attempts live in a signed cookie keyed from `plone.keyring`, the way `plone.session` keys its auth tickets: Plone 6.2 ships no `session_data_manager`, and an unsigned cookie would let a browser choose which flow it is completing.

A userid is minted once and stored. It is a random uuid4 by default — it leaks nothing and never has to change — but a provider can be configured to mint a readable one instead, from the provider's username, the email address or the provider's subject, so a GitHub account arrives as `ericof` rather than 32 hex characters. All three are claims, so all three are handled: the value is normalized into something usable as an id, an empty one falls back to a uuid rather than minting something unusable, and one already taken gets a numeric suffix. Availability is checked against **every** PAS source, not just this package's records: otherwise a provider account called `admin` would be handed the site's `admin` userid and inherit its roles. The GitHub and `plone-identity` drivers default to the provider's username, since both publish one that is already the name the person is known by.

Auto-linking by verified email is opt-in per provider, and matches only addresses this site verified itself with a magic link. A provider asserting `email_verified` is not enough — trusting it would make an account takeover as cheap as an unverified address at any provider a site happens to have configured.

Provider metadata is resolved once and cached per issuer: published endpoint constants for providers that do not move, OIDC discovery for the rest, so a login costs one round trip rather than three. Which of the two a provider gets is asked of its driver — does it declare an `issuer` field for the operator to fill in — rather than looked up in a list of driver ids, so a driver this package has never heard of is discovered correctly and a subclass is not refused for being one. The token-endpoint authentication method comes from that discovery document rather than authlib's default, and the `id_token` audience is validated against the client id configured for the provider rather than the one the provider advertises. @ericof
