A provider that offers several addresses no longer has one picked for it; the user is asked which is theirs.

GitHub returns every address on an account, and the previous release chose among them — the primary verified one, then any verified one, then an unverified primary. That is a guess about which identity the person is here as, and it is not a harmless one: the address is what a verified-email link matches on, so choosing decides which existing account a new GitHub identity would attach to.

One address is still an answer. An account with a single usable address has nothing to decide, so it is used exactly as a provider that sent one address would be, and nobody is asked anything. An account with more than one is now carried forward instead: the driver attaches the list to the claims under a key of this package's own, `email` is left empty, and nothing is reported as verified. The profile is therefore minted `incomplete` and the required-information gate holds its owner on the edit form — which is where the question gets asked.

Two endpoints answer with the list, from one gathering so they cannot drift. `@my-profile` names the addresses, each with the provider that offered it and that provider's own verification claim, so a frontend can explain why it is asking. `@types` puts them in the `email` field's schema as `enum`/`enumNames`/`choices` — the trio `plone.restapi` emits for a `Choice` field — so the form renders a list rather than an empty box. Addresses from several linked providers are gathered into one question and deduplicated, since the same address from two providers is one answer. The offer stops once the profile carries an address.

Advisory rather than binding, deliberately: the field is a `TextLine` either way, so a `PATCH` carrying an address that was never offered is still accepted. The list is what the person was handed, not the set of addresses they are allowed to have. A provider's `verified` flag is carried to be shown and never acted on — only an address this site confirmed with a magic link counts as verified anywhere here. @ericof
