Groups can contain groups, and membership is a behavior rather than a field on one type.

`group_ids` has moved off the Profile schema into `pas.plugins.identity.group_membership`, a schema-only behavior in a **Groups** fieldset. The storage is unchanged -- the field still lives on the content object, the catalog still indexes it, and `profile.group_ids` still answers -- but it is now something a type opts into. A site running its own user type gets membership without redeclaring the field, its vocabulary and its two permissions and then keeping all three in step by hand.

The Group type enables the same behavior, and there `group_ids` means the groups that *group* belongs to. Everybody in an inner group is therefore in every group it names, the way a GitHub child team inherits its parent team's access. Membership stays a fact stored on the member whether the member is a person or a group, so nesting is a walk over one field rather than a second kind of edge.

This was refused once, on the grounds that a group whose members are groups makes `getGroupsForPrincipal` recursive and that a recursive answer computed from catalog metadata stops being a single lookup. The first half is true and the second turned out not to matter: the recursion is over the group graph, which grows with the number of teams rather than with the number of people, and one catalog query returns all of it. A cycle is an ordinary input rather than an error -- two edit forms that each looked reasonable can produce one -- and the walk terminates on it instead of refusing the second edit for a reason about the first. A deactivated group neither grants nor conducts: cutting it removes the access of everybody who reached something through it.

`GET @group-members/<id>` is the contextual version of a listing plone.restapi already half-answers. `@groups/<id>` carries member userids and, going through PlonePAS, already sees the nesting; what it cannot do is name each person, search within the group, or say what feeds into it. This does all three from the Profile catalog in one query, and reports `nested_groups` and `parent_groups` so a group page needs no request per level. A manager may read any group; anybody else may read a group they are in.
