Added optional copying of a provider's avatar into Plone's portrait storage, **off by default**. When switched on, a changed `picture_url` claim is fetched during claims sync and stored as the user's picture.

Where that is depends on the site, and it is the same answer a preferences upload gets: the Profile on a site running the `[profile]` layer, `portal_memberdata` everywhere else. One store per user, whichever writer — an avatar in the other one would leave the Profile content object showing an empty picture field on a site that was displaying a picture. A picture somebody chose is never replaced: the Profile remembers which URL the provider supplied and a provider may replace only its own, so uploading your own ends its claim and clearing yours hands it back.

Off by default because `picture_url` is a claim, and at plenty of providers a claim is whatever the user typed: turning it into a server-side fetch makes the login path a request forger, and a user who sets their avatar URL to an address only the backend can reach gets the backend to fetch it and reads the bytes back through their own portrait. When it is on, the guards are HTTPS only, a short timeout, a size cap read from the stream rather than trusted from a header, and a content type the server actually claims is an image. None of that makes fetching a user-supplied URL safe, which is why the switch exists rather than a longer list of guards.

A provider can be configured to allow plain HTTP as well, off unless somebody sets it. It is per provider rather than a second site-wide record because "this issuer is a container on my own machine with no certificate" is a statement about that issuer; it exists because a development or demo stack could not exercise this path at all otherwise, and a feature nobody can run is a feature nobody has tested. It relaxes exactly one scheme — `file://` is refused either way.

The fetch runs *after* the successful-authentication event rather than before it, and so does the provider's property map. Both are fallbacks — each asks whether something else owns this user's data and writes into core's own store only when the answer is no — and on a first login neither question has an honest answer until the event has been delivered, because the thing that would claim the user is created by a subscriber to it. Asked too early, both were told "nobody owns this user" and wrote to `portal_memberdata`, leaving the claimed store empty on exactly the login that created it; and neither self-corrects, since the property map skips a field that already holds a value and the avatar is refetched only when the provider changes its URL. A fallback runs after everyone entitled to claim has been told.

Every failure is logged and swallowed. An avatar that would not load is a missing picture, and refusing the login over it would be a far worse bug. @ericof
