Every address a provider reports goes onto the Profile, and a provider the operator trusts can verify one.

GitHub returns every address on an account. This used to be treated as a question nobody could answer for the user: none of them was chosen, `email` was left empty, the Profile was minted `incomplete`, and the required-information gate held its owner on the edit form until they picked. That design belonged to a Profile with a single address slot, where filling it was a guess about which identity the person was here as. `emails` is a list, so there is nothing to withhold — all of them go on, in the order the provider offers them, and `email` derives from the list as it already did.

Choosing is arranging. Which address stands for somebody is the order of their list, so a preferred address is moved to the front rather than set in a field of its own — on the edit form, or with **Make preferred** on the sign-in methods page. Nobody is held anywhere to do it.

A later login **appends**, once. An address a provider has already put on is never put on again, so an address somebody deletes stays deleted; the order they arranged is never rearranged; and a provider that changes their address adds the new one beside the old rather than replacing it. Claims carry `emails`, one entry per address with `address`, `verified` and `primary`, and every driver fills it — with the single entry most providers send, so nothing downstream branches on how many there are. `email_choices`, `@my-profile`'s `email_choices` key, and the `@types` decoration that rendered the addresses as a choice are all gone with the question they answered.

**A provider's email verification can now count, where an operator says it does.** `trust_email_verification` is a new per-provider setting: switched on, an address the provider says it verified is recorded here exactly as a magic link records one — an `email` identity in the store, one notion of verified and no second flag to drift. `google` and `github` ship with it on, because neither will call an address verified until the account has answered mail at it; every other driver ships with it off. Telling somebody who just signed in with Google to go and prove the address Google proved was a worse flow for no security.

`auto_link_by_email` now requires it too, which closes a hole rather than opening one: the address auto-linking matches on is the one the incoming provider just sent, so a provider whose word this site does not take could previously reach an account by asserting an address some other, trusted route had verified. Both switches are off by default and both are the operator's.

`email` is no longer a field the claims sync writes, since the addresses have their own path; a property map naming it is ignored for the Profile and still honoured against the Plone user. @ericof
