Added the control-panel API and the registry layout behind it. `GET @identity-drivers` describes every registered driver and its configuration schema, which is what the frontend renders a form from; `@identity-providers` supports full CRUD plus a per-provider connection check. The **Identity providers** entry is registered in `portal_controlpanel`, so Plone's own listing links to it.

Every provider setting is its own registry record — `pas.plugins.identity.providers.<id>.<field>` — rather than one text record holding a JSON list. A GenericSetup export therefore describes a site's providers field by field, a single setting can be changed without rewriting the rest, and `get_provider_record` reads one the way `plone.api.portal.get_registry_record` reads any other.

Each driver's schema is what makes a provider configurable without frontend work: every field declares its type, whether it is secret, its default and an explicit `order`, because a schema travels as a JSON object and plone.restapi serialises those sorted — so the order a driver declares is gone by the time a form is built from it unless each field carries its position. A driver's defaults are applied when a provider is created, which is what keeps a GitHub provider from being configured with OIDC scopes it does not grant, and a driver may seed the new provider's attribute mapping so a provider created without touching it still syncs something.

A provider's scope is a list of permissions rather than the space-delimited string OAuth 2 puts on the wire: with the encoding and the value in one field, a trailing space or a stray comma becomes a scope of its own that the provider rejects as unknown. The attribute mapping is a per-provider record of provider claim to Plone user field, so a claim this package has never heard of can be mapped without code; the `pas.plugins.identity.UserFields` vocabulary lists what can be mapped onto, built from `getFromBaseSchema(IUserDataSchema)` so it includes fields a site added. Stored secrets are masked on the way out and restored on the way back unless edited — symmetrically, including for a provider whose driver has been uninstalled, so a round trip that changes a title cannot silently blank a secret.

The login callback URL is a site-wide setting rather than a per-provider one, since it is one frontend route registered identically with every provider; it accepts a path, resolved against the portal URL, and defaults to `/login-identity`. Reinstalling a layer creates the records its settings interface has gained since the site was set up, so a site that upgrades and reapplies a profile is not left with a control panel that cannot be read. @ericof
