A Profile carries a list of addresses, and `email` is derived from it.

A person has more than one address, signs in with more than one of them, and which one is theirs *here* is a question whose answer changes. So `emails` is what a Profile stores -- an ordered, required tuple -- and `email`, the single value every property sheet, every OIDC claim and every enumeration still reads, is computed: the first verified address, or the first address at all when none is verified. It is read-only, so `plone.restapi` leaves it out of the edit form altogether and there is no second value to disagree with the list. Everything that writes it keeps working: a write moves that address to the front of the list rather than replacing a field, and an empty write is ignored, because a provider that stopped sending an address has not said the person no longer has one.

**Verification is not a field.** An address counts as verified when this site holds an `email` identity for it owned by that userid, which is exactly what a magic link creates and exactly what `auto_link_by_email` already consults. A second `verified` flag beside it would be a copy of that fact, and the two would drift the first time an identity was unlinked. Linking or unlinking an email identity reindexes the owner's Profile, because `email` is served from catalog metadata everywhere it matters and confirming a link never touches the Profile.

**Verifying an address now requires it to be yours.** `POST @identities` with the email provider refuses an address that is not on the caller's profile. A magic link proves control of whatever was typed, so the free-text box the identities page used to offer verified *any* mailbox -- and a verified address is what `auto_link_by_email` attaches a new provider account to. Naming the address on your profile first makes it a claim somebody can see and an administrator can audit. A caller with no Profile is not held to it.

The Profile catalog gains an `emails` KeywordIndex and `emails` / `verified_emails` metadata, so "whose profile carries this address" is one query. `@my-profile` reports `emails` -- each address with whether this site has verified it and which one `email` resolves to.
