Added `/identities` and the user-menu entries that lead to it. A signed-in user can see their sign-in methods, add another, and remove one — with the remove button disabled and explained when it is their last way in, rather than failing only once pressed. The page loads in one request rather than two: `@identities` carries the available providers as an expanded component.

Who is signed in is now shown on the toolbar button that opens the personal-tools menu, as a portrait or as initials on a colour derived from the userid. Volto drew a generic user icon there and a 96px portrait inside the menu — or, for the many users who have never uploaded one, a camera icon: the same picture for everybody, saying "no image here" rather than "this is you". The colour comes from the userid rather than the name, so correcting the spelling of your own name does not change it, and nothing is stored to keep it stable.

The menu itself is now an ordered list of plugs, Volto's own three entries included. It used to be three fixed entries with a pluggable after them, so an add-on could only append: wanting an entry *between* two of Volto's, or wanting one of them gone, meant shadowing the component. "Sign-in methods" sits straight after "Preferences", because choosing how you get in is one; Site Setup stays last, because it is about the site rather than the person. A user who has a Profile gets it under "Profile", in Volto's slot, since for them the content object is where their fields live; on a site without the layer, and for a user first login has not minted one for, Volto's entry keeps the slot and leads to the member form, which is where *those* users' fields really are.

The condition is having a Profile, and it is worth saying why it is not the `source` field `@users` reports. Every account this package creates lives in `source_users`: the layer's PAS plugin serves properties and enumeration, it does not authenticate. So a user whose fields are entirely in a Profile still reports `"source": "source_users"`, and a rule keyed on that hides the entry for everybody. The plugin sits above `mutable_properties`, so wherever a Profile exists it is what answers for that user's fields — having one and being backed by one are the same condition.

All of it reads one store the add-on fills. Volto fetches the current user only when the menu opens and clears it around itself, so nothing outside the menu could rely on knowing who is signed in; a component mounted on every route now reads `@users/<userid>` once per user, carrying the `identities`, `source` and `profile_url` this package's serializer adds.

**This shadows two Volto components**, `Toolbar` and `PersonalTools`, because Volto has no extension point for the avatar: `toolbar-personal` is a DOM id on a button rather than a pluggable. `PersonalTools` is a TypeScript rewrite rather than a copy with a patch — it is this package's code once shadowed, and carrying a verbatim copy made every improvement look like drift — and both carry a header naming the Volto version they were taken from and what differs, so an upgrade is a diff against upstream rather than a re-reading. @ericof
