"""Generate placeholder images for screenshots not captured yet.

Each placeholder carries, written into the image itself, the filename and the
description of the screen to capture — so whoever captures it can identify the
target from the thumbnail without opening the Markdown.

When the real screenshot is taken it simply overwrites the file. No page changes.

Usage::

    uv run --group screenshots python scripts/generate_placeholders.py

The screens to generate are **discovered in the Markdown itself**: the script
scans ``docs/`` for ``image`` directives pointing at ``_static/screens/`` and
uses the ``:alt:`` text as the description. There is no list to keep in two
places.

Existing files that are **not** placeholders are preserved — see
:func:`is_placeholder`.
"""

from pathlib import Path
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont
from PIL import PngImagePlugin

import re
import sys


DOCS = Path(__file__).resolve().parent.parent / "docs"
DESTINATION = DOCS / "_static" / "screens"

#: Browser window size. Placeholders match it so that replacing one with a real
#: capture does not change the framing of a page already written.
WIDTH = 1440
HEIGHT = 810

BACKGROUND = (241, 243, 245)
BORDER = (173, 181, 189)
TEXT = (52, 58, 64)
MUTED = (134, 142, 150)
BAND = (222, 226, 230)

#: Written into the PNG metadata to tell a placeholder from a real capture.
MARK = "pas-plugins-identity-docs:placeholder"

FONTS = [
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/Library/Fonts/Arial.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
]

MONO = [
    "/System/Library/Fonts/Menlo.ttc",
    "/System/Library/Fonts/Supplemental/Courier New.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]

#: Matches the filename in ``{image} .../screens/<name>.png`` and, on the line
#: below, the ``:alt:`` option.
PATTERN = re.compile(
    r"\{image\}\s+\S*/screens/(?P<name>[\w-]+)\.png\s*\n\s*:alt:\s*(?P<alt>.+)"
)


def discover() -> dict[str, str]:
    """Find every screenshot the Markdown references.

    :returns: A mapping of ``{name: description}``, sorted by name.
    """
    found: dict[str, str] = {}
    for page in sorted(DOCS.rglob("*.md")):
        for match in PATTERN.finditer(page.read_text()):
            found[match.group("name")] = match.group("alt").strip()
    return dict(sorted(found.items()))


def is_placeholder(path: Path) -> bool:
    """Report whether a file is a placeholder generated by this script.

    The check reads the mark written into the PNG metadata, so a real capture is
    never overwritten.

    :param path: File to check.
    :returns: ``True`` when the file is missing or was generated here.
    """
    if not path.exists():
        return True
    try:
        with Image.open(path) as img:
            return img.info.get("Comment") == MARK
    except OSError:
        return False


def load_font(candidates: list[str], size: int) -> ImageFont.FreeTypeFont:
    """Load the first available font from a list of candidates.

    :param candidates: Font paths, in order of preference.
    :param size: Point size.
    :returns: The loaded font, or Pillow's default if none exists.
    """
    for path in candidates:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                continue
    return ImageFont.load_default(size)


def wrap(text: str, font: ImageFont.FreeTypeFont, limit: int) -> list[str]:
    """Break text into lines that fit the given width.

    :param text: Text to wrap.
    :param font: Font used to measure.
    :param limit: Maximum width in pixels.
    :returns: The lines.
    """
    lines: list[str] = []
    current = ""
    for word in text.split():
        candidate = f"{current} {word}".strip()
        if font.getlength(candidate) <= limit:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def generate(name: str, description: str) -> bool:
    """Generate one placeholder.

    :param name: Filename, without extension.
    :param description: Text drawn on the image, from the ``:alt:`` option.
    :returns: ``True`` when a file was written, ``False`` when a real capture
        was left alone.
    """
    path = DESTINATION / f"{name}.png"
    if not is_placeholder(path):
        return False

    image = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
    draw = ImageDraw.Draw(image)
    draw.rectangle([(0, 0), (WIDTH - 1, HEIGHT - 1)], outline=BORDER, width=2)
    draw.rectangle([(0, 0), (WIDTH - 1, 56)], fill=BAND)

    title_font = load_font(FONTS, 34)
    body_font = load_font(FONTS, 22)
    mono_font = load_font(MONO, 18)

    draw.text((24, 16), "Screenshot not captured yet", font=body_font, fill=MUTED)

    y = 220
    for line in wrap(description, title_font, WIDTH - 160):
        draw.text((80, y), line, font=title_font, fill=TEXT)
        y += 46

    draw.text((80, y + 30), f"{name}.png", font=mono_font, fill=MUTED)

    meta = PngImagePlugin.PngInfo()
    meta.add_text("Comment", MARK)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, pnginfo=meta)
    return True


def main() -> int:
    """Generate a placeholder for every referenced screenshot that lacks one.

    :returns: Process exit code.
    """
    screens = discover()
    if not screens:
        print("No screenshots referenced in docs/. Nothing to do.")
        return 0

    written = sum(generate(name, text) for name, text in screens.items())
    print(f"{len(screens)} screenshots referenced; {written} placeholders written.")
    if written < len(screens):
        print(f"{len(screens) - written} already captured, left alone.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
