[project]
name = "pas-plugins-identity-docs"
description = "Multi-provider external authentication for Plone, built on authlib."
version = "1.0.0"
keywords = [
    "documentation",
    "Plone",
    "Diátaxis",
]
readme = "README.md"
requires-python = "==3.14.*"
license = { file = "LICENSE.md" }
maintainers = [
    { name = "Érico Andrei", email = "ericof@plone.org" },
]
authors = [
    { name = "Érico Andrei", email = "ericof@plone.org" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pas-plugins-identity",
]

[dependency-groups]
dev = [
    "graphviz",
    "linkify-it-py",
    "myst-parser",
    "plone-sphinx-theme",
    "sphinx-autobuild",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-examples",
    "sphinx-notfound-page",
    "sphinx-reredirects",
    "sphinx-sitemap",
    "sphinx-tippy",
    "sphinxcontrib-httpdomain",
    "sphinxcontrib-httpexample",
    "sphinxcontrib-mermaid",
    "sphinxext-opengraph",
    "vale",
]

[project.urls]
Repository = "https://github.com/collective/pas-plugins-identity"
Documentation = "https://collective.github.io/pas-plugins-identity/"

[tool.uv.sources]
pas-plugins-identity = { path = "../backend/", editable = true }
